# Generated by Django 3.2.12 on 2023-03-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.CharField(default='number', max_length=500),
        ),
    ]
