# Generated by Django 3.2.12 on 2023-03-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_goals',
            field=models.IntegerField(default=0),
        ),
    ]
