# Generated by Django 3.2.12 on 2023-03-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_auto_20230303_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
