# Generated by Django 3.2.12 on 2023-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
